language: python
python: 3.6.7
install:
- pip install -r requirements.txt
- pip install -q Django==$DJANGO_VERSION
script:
- python manage.py test
env:
- DJANGO_VERSION=1.8.5
deploy:
  provider: heroku
  api_key:
    secure: XinFEfMl62jAxyajXXT77+M8EWPPXq+67qjF9hX5fySPyfshDmHD8Ri+SmDlasWA0mOmab2qKqqSsEq6RPWAUNgjHryb7pl+1Dwu//50dSs5sSyZSaMsYl+jfnoIABXrAvvhGF2OeN1s1Hd7iUQkiGILAKtACBUToBmAlImKtT72q5ovVKj2XQx9E80WopqeSBTj6DIBZ05SjJakN5XdAGbHrfbrkooz31EWG46eyGLESFBnVjhsamyIRUdcEDMUenvBSngLSnp7xUTwJqu8v+Py6QQtv64GpcfGXV7EfPBr+QzPVyJMEnbSgIZsgZs1g56Bqr0oYd7zzFb1+N/62W4u/4S9XthYflb8VcutC6+w2LrgL6eNvgDa7llbOPurY6u2Rgm5ukMBva8z1Tkd1+BzOX3g/snzOL9Ucua/kmGOcCIWGINvCZarAnkmgzEp+Cq734y4vwy0Aw68dV1PdM/EEaT4IfG2JxhkqZCvURmgb9+2uPjknKz9tLWbwQ/y1MFUe6dzLR4Jf1JQFse0Gz83euE8zIc6x/+Iha6uFdDyCKzzlNc/Mmhr2zIhtLUiDk69r157dXtVWlvuN85pc7xpwj/UVucIG4+HyWwJf6f2CJB1t3nzwSkwWdNMhM2JTG2Ei79yt/i10oZ6xmvSFTsobBXJygeeKVvdw8+a8vQ=
  app: lab111111
